import {
  brighton,
  tyson,
  blakec,
  ryker,
  carson,
  kamden,
  razorbackLogo,
  austin,
  spencer,
  blakey,
  kalen,
  blakeCBat,
  bowenCatch,
  brightonFirst,
  brightonBat,
  rykerPitch,
  tysonBat,
  tysonPitch,
  kam,
  blake,
  austin_card,
  carson_card,
  kalen_card,
  spencer_card,
  zach_card
} from "./imagesData";

let localTeamData = [
  {
    id: "8",
    position: "1B, SS, P, OF",
    image: brighton,
    dImage: brightonFirst,
    oImage: brightonBat,
  },
  {
    id: "23",
    position: "1B, 2B, OF",
    image: tyson,
    dImage: tysonPitch,
    oImage: tysonBat,
  },
  {
    id: "5",
    position: "3B, P, OF",
    image: blakec,
    dImage: null,
    oImage: blakeCBat,
  },
  {
    id: "34",
    position: "3B, SS, P",
    image: ryker,
    dImage: rykerPitch,
    oImage: null,
  },
  {
    id: "10",
    position: "SS, OF, P",
    image: carson,
    dImage: carson_card,
    oImage: null,
  },
  {
    id: "26",
    position: "1B, OF, P",
    image: kamden,
    dImage: kam,
    oImage: null,
  },
  {
    id: "27",
    position: "3B, SS, P, OF",
    image: razorbackLogo,
    dImage: zach_card,
    oImage: null,
  },
  {
    id: "47",
    position: "C, 2B, OF",
    image: razorbackLogo,
    dImage: bowenCatch,
    oImage: null,
  },
  {
    id: "45",
    position: "3B, P",
    image: austin,
    dImage: austin_card,
    oImage: null,
  },
  {
    id: "80",
    position: "OF",
    image: spencer,
    dImage: spencer_card,
    oImage: null,
  },
  {
    id: "12",
    position: "2B, SS, OF, C",
    image: blakey,
    dImage: blake,
    oImage: null,
  },
  {
    id: "42",
    position: "2B, 3B, OF",
    image: kalen,
    dImage: kalen_card,
    oImage: null,
  },
];

export default localTeamData;
